camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
  filter:
    create: All tasks
spring:
  h2:
    console:
      enabled: true
  datasource:
    username: sa
    password: password
    url: jdbc:h2:file:./demo